# ML-08 — Capstone Modeling Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/vinukondablessena/flyrank-ml-internship/blob/main/work/notebooks/w05_model.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Method choice and why

*Which method from the toolkit, and why it fits your lane.*

In [33]:
import os

print("Current working directory:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir("."))

Current working directory:
/content/flyrank-ml-internship

Files/folders here:
['README.md', 'work', 'notebooks', 'requirements.txt', '.github', 'skills', 'LICENSE', 'outputs', 'docs', 'submission', 'SETUP.md', 'scripts', '.git', 'data', 'DATA_USE.md', 'AGENTS.md', '.gitignore', 'CLAUDE.md', 'GUIDE.md']

In [34]:
!git clone https://github.com/vinukondablessena/flyrank-ml-internship.git

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 139 (delta 49), reused 93 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (139/139), 1.86 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (49/49), done.

In [35]:
import os

print(os.listdir("/content/flyrank-ml-internship"))

['README.md', 'work', 'notebooks', 'requirements.txt', '.github', 'skills', 'LICENSE', 'outputs', 'docs', 'submission', 'SETUP.md', 'scripts', 'flyrank-ml-internship', '.git', 'data', 'DATA_USE.md', 'AGENTS.md', '.gitignore', 'CLAUDE.md', 'GUIDE.md']

In [36]:
import os

data_path = "/content/flyrank-ml-internship/data"

print("Data folder contents:")
print(os.listdir(data_path))

Data folder contents:
['raw', 'processed']

In [37]:
import os

raw_path = "/content/flyrank-ml-internship/data/raw"

print("Raw folder contents:")
print(os.listdir(raw_path))

Raw folder contents:
['content_refresh_anonymized.csv']

In [38]:
print("All columns:")
for i, col in enumerate(df.columns, start=1):
    print(i, repr(col))

All columns:
1 'content_id'
2 'client_id'
3 'search_volume'
4 'competition'
5 'competition_level'
6 'cpc'
7 'content_type'
8 'main_intent'
9 'word_count'
10 'char_count'
11 'provider_used'
12 'model_used'
13 'impressions_90d'
14 'clicks_90d'
15 'pageviews_90d'
16 'sessions_90d'
17 'users_90d'
18 'engaged_sessions_90d'
19 'ai_sessions_90d'
20 'scroll_events_90d'
21 'days_with_impressions'
22 'days_with_sessions'
23 'impressions_last_30d'
24 'clicks_last_30d'
25 'sessions_last_30d'
26 'impressions_prev_30d'
27 'clicks_prev_30d'
28 'sessions_prev_30d'
29 'content_age_days'
30 'age_tier'
31 'age_tier_order'
32 'days_since_last_update'
33 'freshness_tier'
34 'word_count_tier'
35 'char_count_tier'
36 'ctr'
37 'avg_position'
38 'engagement_rate'
39 'scroll_rate'
40 'ai_traffic_pct'
41 'impression_tier'
42 'position_tier'
43 'trend_direction'
44 'trend_pct'
45 'is_declining_label'
46 'log_impressions_90d'
47 'log_clicks_90d'
48 'log_sessions_90d'
49 'log_ai_sessions_90d'
50 'has_clicks'
51 'has_ai_sessions'
52 'measurable_opportunity'

In [39]:
import os

dictionary_path = "/content/flyrank-ml-internship/docs/data-dictionary.md"

print("File exists:", os.path.exists(dictionary_path))

with open(dictionary_path, "r", encoding="utf-8") as f:
    dictionary = f.read()

print(dictionary[:12000])

File exists: True
# Data Dictionary — `content_refresh_anonymized.csv`

One row per content item (page): **30,000 rows × 44 columns**, covering **32 pseudonymized
clients**. All metrics are aggregated over a trailing 90-day window ending at export time.
Keep this file open while you work.

## Read this first — the three rules that prevent 90% of mistakes

1. **Rate columns are ×100 percentages.** `ctr = 0.76` means **0.76%**, not 76%. Applies to
   `ctr`, `engagement_rate`, `scroll_rate`, `ai_traffic_pct`, `trend_pct`.
2. **The label comes from `trend_direction`.** The pipeline defines
   `is_declining_label = (trend_direction == "down")`, so `trend_direction` and `trend_pct`
   must **never** be model features — that's the leakage notebook 02 demonstrates.
3. **IDs are for grouping only.** `content_id` / `client_id` are pseudonyms: use them for
   joins and grouped train/test splits, never as features.

## Identifiers

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `content_id` | text | Pseudonymous page id (`content_` + 12 hex chars) | Unique per row. Grouping/joins only |
| `client_id` | text | Pseudonymous client id (`client_` + 10 hex chars) | 32 distinct values. Use for **client-holdout splits** |

> **Missingness is systematic, not random.** Keyword-context columns are missing along
> `content_type` lines (e.g. `feedly article` rows have no keyword data at all). A blind
> `fillna(0)` therefore encodes content type into your features silently — check missingness
> per content_type before imputing.

## Keyword context (from content metadata)

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `search_volume` | number | Search-volume estimate for the page's target keyword | 0–74,000 in this slice; blank for 2,468 rows with no keyword data |
| `competition` | number | Keyword competition score, 0–1 | Blank when no keyword data |
| `competition_level` | category | `LOW` / `MEDIUM` / `HIGH` | Blank when no keyword data |
| `cpc` | number | Cost-per-click estimate for the target keyword | Blank when no keyword data |
| `content_type` | category | `keyword article` / `feedly article` / `comparison article` | |
| `main_intent` | category | `informational` / `transactional` / `commercial` / `navigational` | Blank when unknown |

## Content properties

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `word_count` | number | Article word count | Blank for 7,699 rows (not measured) |
| `char_count` | number | Article character count | Blank alongside `word_count` |
| `provider_used` | category | LLM provider that generated the article: `openai` / `google` / `other` | Blank when unknown. Not a model feature |
| `model_used` | category | LLM model name (e.g. `gemini-2.5-flash`, `gpt-4o-mini`) | Blank/`unknown` when not recorded. Not a model feature |
| `content_age_days` | number | Days since the content was created | Every row in this slice is ≥ 90 |
| `days_since_last_update` | number | Days since the content was last updated | |

## 90-day activity totals (GSC = Google Search Console, GA4 = Google Analytics)

| Column | Type | Meaning |
|---|---|---|
| `impressions_90d` | number | GSC search impressions (every row in this slice has ≥ 1) |
| `clicks_90d` | number | GSC clicks from search results |
| `pageviews_90d` | number | GA4 pageviews |
| `sessions_90d` | number | GA4 sessions |
| `users_90d` | number | GA4 users |
| `engaged_sessions_90d` | number | GA4 engaged sessions |
| `ai_sessions_90d` | number | GA4 sessions referred from AI tools — **click-throughs from AI assistants, not citations or rankings** |
| `scroll_events_90d` | number | GA4 scroll events |
| `days_with_impressions` | number | Days in the 90-day window with ≥ 1 impression (0–90) |
| `days_with_sessions` | number | Days in the window with ≥ 1 session (0–90) |

## 30-day comparison windows (the trend inputs)

| Column | Type | Meaning |
|---|---|---|
| `impressions_last_30d` | number | Impressions in the most recent 30 days |
| `clicks_last_30d` | number | Clicks, most recent 30 days |
| `sessions_last_30d` | number | Sessions, most recent 30 days |
| `impressions_prev_30d` | number | Impressions in the 30 days before that (days 31–60 back) |
| `clicks_prev_30d` | number | Clicks, days 31–60 back |
| `sessions_prev_30d` | number | Sessions, days 31–60 back |

## Derived rates (all ×100 percentages)

| Column | Formula | Notes |
|---|---|---|
| `ctr` | `clicks_90d / impressions_90d × 100` | 2 decimals. `0.76` = 0.76% |
| `avg_position` | mean GSC position over the window | 1 decimal. Lower is better. **`0` means "no position data", not position zero** (1,205 rows) |
| `engagement_rate` | `engaged_sessions_90d / sessions_90d × 100` | 0–100 |
| `scroll_rate` | `scroll_events_90d / pageviews_90d × 100` | **Can exceed 100** (multiple scroll events per pageview); blank when `pageviews_90d = 0` |
| `ai_traffic_pct` | `ai_sessions_90d / sessions_90d × 100` | **Can exceed 100** (AI-referred sessions are measured independently of total GA4 sessions) |
| `trend_pct` | `(impressions_last_30d − impressions_prev_30d) / impressions_prev_30d × 100` | 1 decimal. Blank when `impressions_prev_30d = 0` (3,388 rows; the prep step fills blanks with 0). **Label source — never a feature** |

## Buckets / tiers (transparent, threshold-based)

| Column | Values | Rule |
|---|---|---|
| `age_tier` | `0-14`, `15-30`, `31-90`, `91-180`, `181-365`, `365+` | From `content_age_days`. This slice only contains `31-90` and up |
| `age_tier_order` | 1–6 | Numeric order of `age_tier` (1 = youngest) |
| `freshness_tier` | `never`, `0-30`, `31-90`, `91-180`, `181+` | From `days_since_last_update`; `never` = no update recorded (0 rows in this slice) |
| `word_count_tier` | `<1000`, `1000-2000`, `2000-3500`, `3500+` | Blank when `word_count` is blank |
| `char_count_tier` | `<8000`, `8000-15000`, `15000-25000`, `25000+` | Blank when `char_count` is blank |
| `impression_tier` | `no_data`, `none`, `low`, `moderate`, `good`, `excellent` | `no_data` = client has no GSC; `none` = 0; `low` > 0; `moderate` ≥ 300; `good` ≥ 3,000; `excellent` ≥ 30,000 |
| `position_tier` | `no_data`, `top_3`, `page_1`, `striking`, `page_3_5`, `deep` | avg position ≤ 3 / ≤ 10 / ≤ 20 / ≤ 50 / > 50. ⚠️ Tier metrics need a volume floor: this slice's `top_3` stratum has median volume ~53 impressions/90d, where one click moves CTR by ~1.9pp — at warehouse scale positions 1–3 run ≈ 2.78% CTR. Never read a tier median without stating its volume floor |
| `trend_direction` | `new`, `flat`, `up`, `down`, `stable` | last-30d vs prev-30d impressions: `new` = prev 0 & last > 0; `flat` = both 0; `up` > +20%; `down` < −20%; else `stable`. **Label source — never a feature** |

## Columns the prep step adds (44 → 52 in `refresh_feature_vector.csv`)

`scripts/01_prepare_features.py` fills blanks (numerics → 0, categoricals → `"unknown"`) and adds:

| Column | Meaning |
|---|---|
| `is_declining_label` | **The target.** 1 when `trend_direction == "down"` (16,262 rows = 54.2%), else 0 |
| `log_impressions_90d`, `log_clicks_90d`, `log_sessions_90d`, `log_ai_sessions_90d` | `log1p` of the raw totals (traffic is heavy-tailed) |
| `has_clicks` | 1 when `clicks_90d > 0` |
| `has_ai_sessions` | 1 when `ai_sessions_90d > 0` |
| `measurable_opportunity` | 1 when `impressions_90d ≥ 100` and `sessions_90d > 0` |

Which of the 52 columns the models actually use is defined in one place:
`MODEL_NUMERIC_FEATURES` and `MODEL_CATEGORICAL_FEATURES` in `scripts/ml_utils.py`.

---

# The full warehouse release (weeks 3+)

The starter CSV above is a 30k-row teaching slice. Lane and capstone work run on the **full
pseudonymized warehouse release** — ~79M rows of daily search performance hosted as Parquet on
Hugging Face (gated; notebook 03 walks through access and the DuckDB workflow).

## Tables

| Table | Grain | Use it for |
|---|---|---|
| `dim_clients` | one row per pseudonymized client | history coverage (`gsc_data_start`, `ga4_data_start`), access profile |
| `dim_content` | one row per pseudonymized content item | content metadata, keyword context, joins |
| `fact_content_daily_performance` | report_date × client × content | time-series features, trend labels, forward-window validation. Partitioned by `month=YYYY-MM` |
| `fact_content_query_90d` | client × content × query hash (fixed 90-day window) | query-mix features: diversity, concentration, rare/anonymized tail |

## The three things to know before modeling it

1. **Unbalanced panel.** Per-client history depth differs (some clients have 17 months, some 3).
   `dim_clients.gsc_data_start` is the honest per-client start date — always check it before
   defining a time window, and prefer per-client windows over one global calendar window.
2. **GSC-only early history — and the flags are THREE-valued.** Rows before a client's
   `ga4_data_start` have GA4 columns zero-filled with `ga4_data_available = FALSE` — filter on
   the flag, don't treat zeros as "no engagement". But the flag can also be **NULL** (millions
   of rows carry `ga4_data_available` NULL with NULL metrics — neither zero-filled nor flagged
   FALSE, and 10 of 104 clients have NULL access flags in `dim_clients`). `= FALSE` or `NOT …`
   silently mishandles them: always filter with `IS TRUE` / `IS NOT TRUE` (same for the GSC
   twin).
> ⚠️ **Leakage watch — the query table's window overlaps recent months.**
> `fact_content_query_90d` covers a fixed 90-day window (the most recent ~3 months of the
> snapshot). If your capstone predicts something about *those* months (e.g. "will this page
> decline next month?"), the `impressions_90d` / `*_last30` columns **contain your label period**
> — using them is leakage. Only the `*_prev30` columns are safe as features for a label defined
> on the final month. Always line up your feature window and label window against this table's
> window before you use it.

3. **The query table is internally complete — and *almost* fact-reconciled.** Per content item,
   kept rows (≥ 10 impressions) + `rare_impressions_share` + `anonymized_impressions_share`
   account for exactly 100% of `content_total_impressions_90d`. Against the daily fact summed
   over the same window, ~98.5% of content items match exactly; the rest are items registered
   to the platform **mid-window** — the daily fact only accrues history from registration day,
   while the query table attributes the full window using the current URL map. Treat
   `content_total_impressions_90d` as the query table's own denominator. Grain guard: the
   per-content context columns repeat on every row of that content item — `ANY_VALUE()` them,
   never `SUM()`.

In [40]:
import os

for root, dirs, files in os.walk("/content/flyrank-ml-internship"):
    for file in files:
        if "refresh_feature" in file.lower():
            print(os.path.join(root, file))

/content/flyrank-ml-internship/data/processed/refresh_feature_vector.csv

In [41]:
script_path = "/content/flyrank-ml-internship/scripts/01_prepare_features.py"

with open(script_path, "r", encoding="utf-8") as f:
    script = f.read()

print(script)

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from ml_utils import (
    BOOLEAN_COLUMNS,
    CATEGORICAL_COLUMNS,
    MODEL_CATEGORICAL_FEATURES,
    MODEL_NUMERIC_FEATURES,
    NUMERIC_COLUMNS,
    PROCESSED_DIR,
    RAW_PATH,
    display_path,
    ensure_dirs,
    to_bool_series,
    write_json,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare FlyRank refresh feature vector.")
    parser.add_argument("--input", default=str(RAW_PATH), help="Raw anonymized CSV export.")
    parser.add_argument(
        "--output",
        default=str(PROCESSED_DIR / "refresh_feature_vector.csv"),
        help="Prepared feature-vector CSV.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    ensure_dirs()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(
            f"Raw input not found: {input_path}. Restore data/raw/content_refresh_anonymized.csv from git "
            "(mentor repos can re-export it with 00_export_bigquery_anonymized.mjs)."
        )

    df = pd.read_csv(input_path)
    initial_rows = len(df)

    required = ["content_id", "client_id", "impressions_90d", "sessions_90d", "content_age_days", "trend_direction"]
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    for column in NUMERIC_COLUMNS:
        if column in df.columns:
            df[column] = pd.to_numeric(df[column], errors="coerce")
        else:
            df[column] = 0

    for column in BOOLEAN_COLUMNS:
        if column in df.columns:
            df[column] = to_bool_series(df[column])
        else:
            df[column] = False

    for column in CATEGORICAL_COLUMNS:
        if column in df.columns:
            df[column] = df[column].fillna("unknown").astype(str).replace({"": "unknown", "nan": "unknown"})
        else:
            df[column] = "unknown"

    numeric_fill_zero = [
        "search_volume",
        "competition",
        "cpc",
        "word_count",
        "char_count",
        "impressions_90d",
        "clicks_90d",
        "pageviews_90d",
        "sessions_90d",
        "users_90d",
        "engaged_sessions_90d",
        "ai_sessions_90d",
        "scroll_events_90d",
        "days_with_impressions",
        "days_with_sessions",
        "impressions_last_30d",
        "clicks_last_30d",
        "sessions_last_30d",
        "impressions_prev_30d",
        "clicks_prev_30d",
        "sessions_prev_30d",
        "content_age_days",
        "age_tier_order",
        "days_since_last_update",
        "ctr",
        "avg_position",
        "engagement_rate",
        "scroll_rate",
        "ai_traffic_pct",
        "trend_pct",
    ]
    for column in numeric_fill_zero:
        df[column] = df[column].replace([np.inf, -np.inf], np.nan).fillna(0)

    df = df[(df["impressions_90d"] > 0) & (df["content_age_days"] >= 90)].copy()
    df = df.drop_duplicates(subset=["content_id"]).reset_index(drop=True)

    df["is_declining_label"] = df["trend_direction"].str.lower().eq("down").astype(int)

    df["log_impressions_90d"] = np.log1p(df["impressions_90d"])
    df["log_clicks_90d"] = np.log1p(df["clicks_90d"])
    df["log_sessions_90d"] = np.log1p(df["sessions_90d"])
    df["log_ai_sessions_90d"] = np.log1p(df["ai_sessions_90d"])
    df["has_clicks"] = (df["clicks_90d"] > 0).astype(int)
    df["has_ai_sessions"] = (df["ai_sessions_90d"] > 0).astype(int)
    df["measurable_opportunity"] = (
        (df["impressions_90d"] >= 100) & (df["sessions_90d"] > 0)
    ).astype(int)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)

    metadata = {
        "input": display_path(input_path),
        "output": display_path(output_path),
        "initial_rows": int(initial_rows),
        "prepared_rows": int(len(df)),
        "declining_rows": int(df["is_declining_label"].sum()),
        "declining_rate": float(df["is_declining_label"].mean()) if len(df) else 0.0,
        "model_numeric_features": MODEL_NUMERIC_FEATURES,
        "model_categorical_features": MODEL_CATEGORICAL_FEATURES,
        "target_definition": "trend_direction == 'down'",
    }
    write_json(PROCESSED_DIR / "feature_metadata.json", metadata)

    print(f"Prepared {len(df):,} rows from {initial_rows:,} raw rows")
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()

In [42]:
%cd /content/flyrank-ml-internship

/content/flyrank-ml-internship

In [43]:
!python scripts/01_prepare_features.py

Prepared 30,000 rows from 30,000 raw rows
Wrote /content/flyrank-ml-internship/data/processed/refresh_feature_vector.csv

In [44]:
import pandas as pd
import os

PROCESSED_PATH = "/content/flyrank-ml-internship/data/processed/refresh_feature_vector.csv"

print("File exists:", os.path.exists(PROCESSED_PATH))

df = pd.read_csv(PROCESSED_PATH)

print("Shape:", df.shape)

print("\nTarget distribution:")
print(df["is_declining_label"].value_counts())

print("\nTarget rate:")
print(df["is_declining_label"].mean())

print("\nFirst 10 columns:")
print(df.columns[:10].tolist())

File exists: True
Shape: (30000, 52)

Target distribution:
is_declining_label
1    16262
0    13738
Name: count, dtype: int64

Target rate:
0.5420666666666667

First 10 columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count']

In [45]:
import sys

sys.path.insert(0, "/content/flyrank-ml-internship/scripts")

from ml_utils import MODEL_NUMERIC_FEATURES, MODEL_CATEGORICAL_FEATURES

print("Numeric features:")
print(MODEL_NUMERIC_FEATURES)

print("\nNumber of numeric features:", len(MODEL_NUMERIC_FEATURES))

print("\nCategorical features:")
print(MODEL_CATEGORICAL_FEATURES)

print("\nNumber of categorical features:", len(MODEL_CATEGORICAL_FEATURES))

Numeric features:
['search_volume', 'competition', 'cpc', 'word_count', 'char_count', 'log_impressions_90d', 'log_clicks_90d', 'log_sessions_90d', 'log_ai_sessions_90d', 'days_with_impressions', 'days_with_sessions', 'content_age_days', 'days_since_last_update', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct']

Number of numeric features: 18

Categorical features:
['competition_level', 'content_type', 'main_intent', 'age_tier', 'freshness_tier', 'word_count_tier', 'impression_tier', 'position_tier']

Number of categorical features: 8

In [46]:
# Leakage and ID checks

LEAKAGE_COLUMNS = {
    "trend_direction",
    "trend_pct",
    "content_id",
    "client_id",
    "is_declining_label"
}

all_features = list(MODEL_NUMERIC_FEATURES) + list(MODEL_CATEGORICAL_FEATURES)

leakage_found = [col for col in all_features if col in LEAKAGE_COLUMNS]

print("Total model features:", len(all_features))
print("Leakage/ID columns found in feature lists:", leakage_found)

print("\nTarget column present in dataset:", "is_declining_label" in df.columns)
print("Client column present:", "client_id" in df.columns)

print("\nNumber of unique clients:", df["client_id"].nunique())

Total model features: 26
Leakage/ID columns found in feature lists: []

Target column present in dataset: True
Client column present: True

Number of unique clients: 32

In [47]:
from sklearn.model_selection import GroupShuffleSplit

TARGET = "is_declining_label"

X = df.drop(columns=[TARGET])
y = df[TARGET]
groups = df["client_id"]

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(gss.split(X, y, groups=groups))

train_df = df.iloc[train_idx].copy()
test_df = df.iloc[test_idx].copy()

print("Train rows:", len(train_df))
print("Test rows:", len(test_df))

print("\nTrain clients:", train_df["client_id"].nunique())
print("Test clients:", test_df["client_id"].nunique())

print("\nClients appearing in BOTH sets:")
print(set(train_df["client_id"]) & set(test_df["client_id"]))

print("\nTrain target rate:", train_df[TARGET].mean())
print("Test target rate:", test_df[TARGET].mean())

Train rows: 23837
Test rows: 6163

Train clients: 25
Test clients: 7

Clients appearing in BOTH sets:
set()

Train target rate: 0.5501111717078492
Test target rate: 0.5109524582184002

We use Logistic Regression as the first learned model because this is a binary classification problem: predicting whether a content item is declining (`is_declining_label = 1`). Logistic Regression is a simple and interpretable baseline for a learned model, so it gives us a clear comparison against the Week-4 rule baseline without rewarding unnecessary complexity. We use the prepared feature set from the repository and exclude the label source (`trend_direction` and `trend_pct`) and IDs from the model features.

## 2. Split design

*Grouped by client? Time-aware? Say why this split is honest for your question.*

We use a client-grouped 80/20 train/test split with a fixed random seed of 42. Entire clients are held out from the test set, so no client appears in both training and testing. This is more honest than a random row split because multiple content items belong to the same client and could otherwise create overly optimistic results. The model and Week-4 baseline will be evaluated on the same held-out test data and the same metric.

In [48]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

# Features from the official FlyRank feature lists
numeric_features = list(MODEL_NUMERIC_FEATURES)
categorical_features = list(MODEL_CATEGORICAL_FEATURES)

X_train = train_df[numeric_features + categorical_features]
y_train = train_df[TARGET]

X_test = test_df[numeric_features + categorical_features]
y_test = test_df[TARGET]

# Numeric preprocessing
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

# Categorical preprocessing
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# Logistic Regression
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            LogisticRegression(
                max_iter=1000,
                class_weight="balanced",
                random_state=42
            )
        )
    ]
)

model.fit(X_train, y_train)

print("Model trained successfully.")
print("Training rows:", len(X_train))
print("Test rows:", len(X_test))

Model trained successfully.
Training rows: 23837
Test rows: 6163

In [49]:
from sklearn.metrics import precision_score, accuracy_score, roc_auc_score

# Predicted probability of the declining class
test_prob = model.predict_proba(X_test)[:, 1]

# Predicted class using the default 0.5 threshold
test_pred = (test_prob >= 0.5).astype(int)


def precision_at_k(y_true, scores, k):
    y_true = np.asarray(y_true)
    scores = np.asarray(scores)

    # Highest-risk items first
    top_k_idx = np.argsort(scores)[::-1][:k]

    return y_true[top_k_idx].mean()


p20 = precision_at_k(y_test.values, test_prob, 20)
p50 = precision_at_k(y_test.values, test_prob, 50)

accuracy = accuracy_score(y_test, test_pred)
roc_auc = roc_auc_score(y_test, test_prob)

print("Logistic Regression results")
print("---------------------------")
print(f"Precision@20: {p20:.4f}")
print(f"Precision@50: {p50:.4f}")
print(f"Accuracy:     {accuracy:.4f}")
print(f"ROC-AUC:      {roc_auc:.4f}")

Logistic Regression results
---------------------------
Precision@20: 0.7000
Precision@50: 0.7200
Accuracy:     0.5832
ROC-AUC:      0.6158

In [50]:
import os

print("Searching for baseline_action_score.csv...")

for root, dirs, files in os.walk("/content/flyrank-ml-internship"):
    for file in files:
        if "baseline" in file.lower() or "action_score" in file.lower():
            print(os.path.join(root, file))

Searching for baseline_action_score.csv...
/content/flyrank-ml-internship/work/notebooks/w04_baseline_score.ipynb
/content/flyrank-ml-internship/scripts/02_baseline_score.py
/content/flyrank-ml-internship/flyrank-ml-internship/work/notebooks/w04_baseline_score.ipynb
/content/flyrank-ml-internship/flyrank-ml-internship/scripts/02_baseline_score.py
/content/flyrank-ml-internship/data/processed/baseline_metadata.json
/content/flyrank-ml-internship/data/processed/baseline_refresh_queue.csv

In [51]:
baseline_script = "/content/flyrank-ml-internship/scripts/02_baseline_score.py"

with open(baseline_script, "r", encoding="utf-8") as f:
    baseline_code = f.read()

print(baseline_code)

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from ml_utils import PROCESSED_DIR, normalize, percentile_rank, write_json


FEATURE_PATH = PROCESSED_DIR / "refresh_feature_vector.csv"
OUTPUT_PATH = PROCESSED_DIR / "baseline_refresh_queue.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build deterministic refresh baseline score.")
    parser.add_argument("--input", default=str(FEATURE_PATH))
    parser.add_argument("--output", default=str(OUTPUT_PATH))
    return parser.parse_args()


def reason_codes(row: pd.Series) -> list[str]:
    reasons: list[str] = []
    if row["days_since_last_update"] >= 180 and row["impressions_90d"] >= 500:
        reasons.append("stale_visible_page")
    if row["trend_direction"].lower() == "down" and row["impressions_90d"] >= 100:
        reasons.append("declining_with_demand")
    if row["word_count"] > 0 and row["word_count"] < 1200 and row["impressions_90d"] >= 250:
        reasons.append("thin_visible_page")
    if row["avg_position"] > 0 and row["avg_position"] <= 10 and row["content_age_days"] >= 180:
        reasons.append("page_one_decay_risk")
    if row["impressions_90d"] >= 500 and 0 < row["avg_position"] <= 20 and row["ctr"] < 0.5:
        reasons.append("low_ctr_visible_page")
    if row["sessions_90d"] >= 30 and (
        (row["engagement_rate"] > 0 and row["engagement_rate"] < 30)
        or (row["scroll_rate"] > 0 and row["scroll_rate"] < 30)
    ):
        reasons.append("low_engagement_visible_page")
    if not reasons:
        reasons.append("general_refresh_review")
    return reasons


def suggested_action(row: pd.Series) -> str:
    reasons = set(str(row["reason_codes"]).split("|"))
    if "thin_visible_page" in reasons:
        return "expand_and_refresh"
    if "low_ctr_visible_page" in reasons:
        return "refresh_and_review_ctr"
    if "stale_visible_page" in reasons or "declining_with_demand" in reasons:
        return "refresh"
    return "monitor"


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.input)
    if df.empty:
        raise ValueError("Feature vector is empty")

    df["visibility_score"] = percentile_rank(np.log1p(df["impressions_90d"]))
    df["freshness_risk_score"] = percentile_rank(df["days_since_last_update"])
    df["position_opportunity_score"] = (
        (1 - normalize(df["avg_position"].clip(lower=1, upper=50)))
        * df["visibility_score"]
        * (df["avg_position"] > 0).astype(int)
    )
    df["depth_gap_score"] = (1 - percentile_rank(df["word_count"])) * df["visibility_score"]

    df["baseline_refresh_score"] = (
        0.40 * df["visibility_score"]
        + 0.30 * df["freshness_risk_score"]
        + 0.25 * df["position_opportunity_score"]
        + 0.05 * df["depth_gap_score"]
    ).clip(0, 1)

    df["reason_codes"] = df.apply(lambda row: "|".join(reason_codes(row)), axis=1)
    df["suggested_action_baseline"] = df.apply(suggested_action, axis=1)
    df["baseline_rank"] = df["baseline_refresh_score"].rank(method="first", ascending=False).astype(int)

    output_columns = [
        "content_id",
        "client_id",
        "baseline_rank",
        "baseline_refresh_score",
        "visibility_score",
        "freshness_risk_score",
        "position_opportunity_score",
        "depth_gap_score",
        "reason_codes",
        "suggested_action_baseline",
        "is_declining_label",
        "impressions_90d",
        "clicks_90d",
        "sessions_90d",
        "avg_position",
        "ctr",
        "engagement_rate",
        "scroll_rate",
        "content_age_days",
        "days_since_last_update",
        "word_count",
        "trend_direction",
    ]

    out = df[output_columns].sort_values("baseline_rank")
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_path, index=False)

    write_json(PROCESSED_DIR / "baseline_metadata.json", {
        "rows": int(len(out)),
        "top_score": float(out["baseline_refresh_score"].max()),
        "median_score": float(out["baseline_refresh_score"].median()),
        "declining_rate_top_50": float(out.head(50)["is_declining_label"].mean()) if len(out) else 0.0,
        "score_formula": {
            "visibility_score": 0.40,
            "freshness_risk_score": 0.30,
            "position_opportunity_score": 0.25,
            "depth_gap_score": 0.05,
        },
    })

    print(f"Wrote baseline queue: {output_path}")
    print(f"Top-50 declining rate (full data, not the evaluated holdout Precision@50): {out.head(50)['is_declining_label'].mean():.3f}")


if __name__ == "__main__":
    main()

In [52]:
%cd /content/flyrank-ml-internship

/content/flyrank-ml-internship

In [53]:
!python scripts/02_baseline_score.py

Wrote baseline queue: /content/flyrank-ml-internship/data/processed/baseline_refresh_queue.csv
Top-50 declining rate (full data, not the evaluated holdout Precision@50): 0.340

In [54]:
import os

for root, dirs, files in os.walk("/content/flyrank-ml-internship"):
    for file in files:
        if "baseline_action_score" in file.lower():
            print(os.path.join(root, file))

In [55]:
import os

print("Outputs folder:")
print(os.listdir("/content/flyrank-ml-internship/outputs"))

print("\nWork folder:")
print(os.listdir("/content/flyrank-ml-internship/work"))

print("\nWork/outputs folder:")
work_outputs = "/content/flyrank-ml-internship/work/outputs"

if os.path.exists(work_outputs):
    print(os.listdir(work_outputs))
else:
    print("work/outputs does not exist")

Outputs folder:
['model_report.md', 'charts', 'refresh_queue_sample.csv']

Work folder:
['capstone_report_template.md', 'README.md', 'notebooks']

Work/outputs folder:
work/outputs does not exist

In [56]:
import json

notebook_path = "/content/flyrank-ml-internship/work/notebooks/w04_baseline_score.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

for i, cell in enumerate(nb["cells"]):
    print(f"\n========== CELL {i} ({cell['cell_type']}) ==========")
    print("".join(cell["source"])[:3000])

========== CELL 0 (markdown) ==========
# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/vinukondablessena/flyrank-ml-internship/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

========== CELL 1 (markdown) ==========
## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*
### My baseline rule

I will rank content pages for refresh review using two observable signals: content freshness and search visibility. Pages that have not been updated for a long time but still have meaningful impressions will receive a higher review score. The rule is intended for decision-support: it identifies pages worth reviewing first, not pages guaranteed to improve after a refresh.

### Reason code

stale_visible_page — the page has been unchanged for at least 180 days and has at least 500 impressions in the observed 90-day window.

========== CELL 2 (code) ==========
!git clone https://github.com/vinukondablessena/flyrank-ml-internship.git

========== CELL 3 (code) ==========
import os

print(os.path.exists("flyrank-ml-internship/data/raw/content_refresh_anonymized.csv"))

========== CELL 4 (code) ==========
import pandas as pd

data_path = "flyrank-ml-internship/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(data_path)

print("Rows:", len(df))
print("Columns:", len(df.columns))
print("\nColumns:")
print(df.columns.tolist())


========== CELL 5 (code) ==========
# Signal check 1: freshness / staleness

df["freshness_bucket"] = pd.cut(
    df["days_since_last_update"],
    bins=[-1, 90, 180, float("inf")],
    labels=["0-90 days", "91-180 days", "181+ days"]
)

freshness_check = (
    df.groupby("freshness_bucket", observed=False)
      .agg(
          n=("content_id", "count"),
          median_impressions_90d=("impressions_90d", "median")
      )
      .reset_index()
)

print(freshness_check)

========== CELL 6 (code) ==========
# Signal check 2: CTR vs Position

df["position_bucket"] = pd.cut(
    df["avg_position"],
    bins=[0, 5, 10, 20, 100],
    labels=["1-5", "6-10", "11-20", "20+"]
)

ctr_check = (
    df.groupby("position_bucket", observed=False)
      .agg(
          n=("content_id", "count"),
          median_ctr=("ctr", "median")
      )
      .reset_index()
)

print(ctr_check)

========== CELL 7 (markdown) ==========
### Signal verdicts

**Signal 1 – Freshness: OPPOSITE**

The observed data does not support the assumption that older pages are more visible. Pages 181+ days since their last update have a median of only 15.5 impressions, compared with 472 impressions for pages updated within 90 days and 1,692 impressions for pages in the 91–180 day bucket. Therefore, staleness alone should not be used as a positive ranking signal in this baseline.

**Signal 2 – CTR vs Position: CONFIRMED**

CTR decreases across the position buckets: median CTR is 0.18 for positions 1–5, 0.14 for positions 6–10, 0.10 for positions 11–20, and 0.00 for positions 20+. This supports using position and CTR together as an observable signal for review prioritization. The result is directional and does not prove that changing CTR will improve ranking.

========== CELL 8 (code) ==========
# Signal check 2: CTR vs Position

df["position_bucket"] = pd.cut(
    df["avg_position"],
    bins=[0, 5, 10, 20, 100],
    labels=["1-5", "6-10", "11-20", "20+"]
)

ctr_check = (
    df.groupby("position_bucket", observed=False)
      .agg(
          n=("content_id", "count"),
          median_ctr=("ctr", "median")
      )
      .reset_index()
)

print(ctr_check)

========== CELL 9 (markdown) ==========
## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*
### Baseline rule

I will rank pages using an observable CTR-position opportunity signal. Pages with meaningful search visibility, positions between 1 and 20, and lower CTR receive higher scores because they have visible search exposure but weaker click-through performance.

The score is a transparent decision-support baseline, not a prediction of guaranteed improvement.

**Reason code:** `ctr_review_candidate`

**Action:** `review_ctr`

**Scoring logic:**
- 40 points if impressions_90d >= 500
- 30 points if average position is between 1 and 10
- 20 points if average position is between 11 and 20
- 10 points if CTR < 0.5

Maximum score = 100.

========== CELL 10 (code) ==========
# Build the baseline score

queue = df.copy()

# Score based only on observable signals
queue["baseline_score"] = (
    (queue["impressions_90d"] >= 500).astype(int) * 40
    + ((queue["avg_position"] >= 1) & (queue["avg_position"] <= 10)).astype(int) * 30
    + ((queue["avg_position"] > 10) & (queue["avg_position"] <= 20)).astype(int) * 20
    + (queue["ctr"] < 0.5).astype(int) * 10
)

# Assign ONE reason code and ONE action
queue["reason_code"] = "ctr_review_candidate"
queue["action"] = "review_ctr"

# Rank highest score first
queue = queue.sort_values(
    ["baseline_score", "impressions_90d"],
    ascending=[False, False]
).reset_index(drop=True)

queue["rank"] = queue.index + 1

# Keep the output public-safe: pseudonymous content ID + score/action/reason
output = queue[
    [
        "rank",
        "content_id",
        "baseline_score",
        "reason_code",
        "action",
        "impressions_90d",
        "avg_position",
        "ctr"
    ]
]

# Create output directory
output_path = Path("flyrank-ml-internship/work/outputs")
output_path.mkdir(parents=True, exist_ok=True)

# Write the required CSV
csv_path = output_path / "baseline_action_score.csv"
output.to_csv(csv_path, index=False)

print("CSV written to:", csv_path)
print("Rows ranked:", len(output))
print("\nTop 10:")
print(output.head(10).to_string(index=False))


========== CELL 11 (markdown) ==========
## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*

========== CELL 12 (markdown) ==========
### Top-20 review

I reviewed the highest-ranked 20 pages from the baseline queue. Each receives the same review action and reason code because this baseline intentionally uses one transparent rule. Confidence is based on the observed visibility, position, and CTR signals. The main failure modes are query mix, SERP features, seasonality, or other context that is not represented in the baseline data.

The review is decision-support only: a high score means the page is worth reviewing first, not that changing the page will necessarily improve performance.

========== CELL 13 (code) ==========
# Top-20 review

top20 = output.head(20).copy()

# Add a confidence note based on observable evidence
top20["confidence_note"] = top20.apply(
    lambda row: (
        "High visibility and page-one position with low CTR."
        if row["impressions_90d"] >= 500 and row["avg_position"] <= 10 and row["ctr"] < 0.5
        else "Visible page with a CTR-position opportunity."
    ),
    axis=1
)

# Add what could make the recommendation wrong
top20["what_would_make_it_wrong"] = (
    "The low CTR may reflect query mix, SERP features, seasonality, "
    "or another context not captured by this baseline."
)

review_columns = [
    "rank",
    "content_id",
    "action",
    "reason_code",
    "baseline_score",
    "impressions_90d",
    "avg_position",
    "ctr",
    "confidence_note",
    "what_would_make_it_wrong"
]

top20_review = top20[review_columns]

print(top20_review.to_string(index=False))


========== CELL 14 (markdown) ==========
## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*

========== CELL 15 (markdown) ==========
### Weak picks and leakage check

Some high-scoring pages may still be weak recommendations because this baseline does not observe query mix, SERP features, seasonality, or other contextual explanations for CTR. A high score therefore means "review first," not "definitely fix."

The baseline uses only current observable fields: impressions_90d, avg_position, and ctr. It does not use product flags, action_type, priority_score, health_score, or future-window outcomes. No client names, URLs, private queries, or raw identifying information are included in the output.

========== CELL 16 (code) ==========
# Weak picks + leakage check

print("=== Weak-pick inspection ===")

# Show the bottom 5 rows among the top 20
print("\nLowest-ranked 5 within the Top-20:")
print(
    top20_review[
        [
            "rank",
            "content_id",
            "baseline_score",
            "impressions_90d",
            "avg_position",
            "ctr"
        ]
    ].tail(5).to_string(index=False)
)

print("\n=== Leakage check ===")

allowed_features = [
    "impressions_90d",
    "avg_position",
    "ctr"
]

forbidden_terms = [
    "health_score",
    "priority_score",
    "action_type",
    "flag",
    "future",
    "label"
]

print("Features used:", allowed_features)

print("\nForbidden product/future terms checked:")
print(forbidden_terms)

print("\nProduct decision fields used in score: NONE")
print("Future-window or target-derived fields used in score: NONE")
print("Leakage check: PASSED")


========== CELL 17 (markdown) ==========
### ML-07 completion check

- Section 1: Two signal checks completed with bucket tables and n.
- Freshness verdict: OPPOSITE.
- CTR vs position verdict: CONFIRMED.
- Section 2: One transparent baseline rule created.
- One reason code: `ctr_review_candidate`.
- One action: `review_ctr`.
- Ranked queue contains 30,000 rows.
- `baseline_action_score.csv` was generated from the notebook.
- Section 3: Top-20 review completed with action, reason code, confidence note, and failure condition.
- Section 4: Weak-pick inspection and leakage check completed.
- No product decision fields were used as features.
- No future-window or target-derived fields were used.
- Claims are framed as observed/directional/decision-support rather than causal.

========== CELL 18 (markdown) ==========
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

## 3. Train + compare vs my baseline

*Same data, same metric, same split as your Week-4 baseline. Show the table.*

In [57]:
# Recreate the exact ML-07 baseline rule on the ML-08 test set

baseline_test = test_df.copy()

baseline_test["baseline_score"] = (
    (baseline_test["impressions_90d"] >= 500).astype(int) * 40
    + (
        (baseline_test["avg_position"] >= 1)
        & (baseline_test["avg_position"] <= 10)
    ).astype(int) * 30
    + (
        (baseline_test["avg_position"] > 10)
        & (baseline_test["avg_position"] <= 20)
    ).astype(int) * 20
    + (baseline_test["ctr"] < 0.5).astype(int) * 10
)

baseline_p20 = precision_at_k(
    baseline_test[TARGET].values,
    baseline_test["baseline_score"].values,
    20
)

baseline_p50 = precision_at_k(
    baseline_test[TARGET].values,
    baseline_test["baseline_score"].values,
    50
)

print("ML-07 Baseline results on ML-08 test set")
print("------------------------------------------")
print(f"Precision@20: {baseline_p20:.4f}")
print(f"Precision@50: {baseline_p50:.4f}")

ML-07 Baseline results on ML-08 test set
------------------------------------------
Precision@20: 0.6500
Precision@50: 0.7400

In [58]:
comparison = pd.DataFrame({
    "Method": [
        "ML-07 Rule Baseline",
        "Logistic Regression"
    ],
    "Precision@20": [
        baseline_p20,
        p20
    ],
    "Precision@50": [
        baseline_p50,
        p50
    ]
})

print(comparison.to_string(index=False))

             Method  Precision@20  Precision@50
ML-07 Rule Baseline          0.65          0.74
Logistic Regression          0.70          0.72

## 4. Errors and interpretation

*Where is the model wrong? What does it lean on? A short error analysis beats a big metric table.*                                               

  ### Error analysis and interpretation

The Logistic Regression model performs better than the ML-07 rule baseline at Precision@20 (0.70 vs 0.65), but the baseline performs better at Precision@50 (0.74 vs 0.72). This suggests that the learned model is useful for prioritizing a very small set of high-risk pages, while the transparent rule remains competitive for a larger review queue.

The model's errors are expected because declining performance can depend on factors that are not fully represented by the available features. Pages may be difficult to classify when their traffic is low, their search position is unstable, or their content characteristics do not clearly distinguish declining from non-declining pages.

Feature interpretation and three concrete incorrect predictions are inspected below. These examples are treated as observed model errors rather than evidence of causation.

In [59]:


feature_names = model.named_steps["preprocessor"].get_feature_names_out()
coefficients = model.named_steps["classifier"].coef_[0]

feature_importance = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients,
    "abs_coefficient": np.abs(coefficients)
}).sort_values("abs_coefficient", ascending=False)

print("Top 10 features by absolute coefficient:")
display(feature_importance.head(10)[["feature", "coefficient"]])

Top 10 features by absolute coefficient:

                              feature  coefficient
5            num__log_impressions_90d     1.425272
51           cat__position_tier_top_3    -0.802077
45           cat__impression_tier_low     0.725328
43     cat__impression_tier_excellent    -0.622277
38     cat__word_count_tier_1000-2000     0.615490
6                 num__log_clicks_90d    -0.571279
29           cat__main_intent_unknown     0.533893
3                     num__word_count     0.508241
21     cat__competition_level_unknown    -0.482846
24  cat__content_type_keyword article     0.451658

### Feature interpretation

The strongest observed model signals are `log_impressions_90d`, `position_tier_top_3`, and `impression_tier_low`. The positive coefficient for `log_impressions_90d` means higher historical impressions are associated with a higher predicted probability of decline in this fitted model. The negative coefficient for `position_tier_top_3` means pages in the top-three position category are associated with a lower predicted probability of decline relative to the reference category.

Other influential features include `impression_tier_low`, `impression_tier_excellent`, `word_count_tier_1000-2000`, and `log_clicks_90d`. These are model associations, not causal effects. The features are plausible because traffic visibility, search position, clicks, and content characteristics can distinguish different types of content performance, but the model does not establish that changing any one feature will cause a page to stop declining.

In [60]:
# Inspect model errors

error_check = test_df[
    ["content_id", "client_id", TARGET]
].copy()

error_check["predicted_probability"] = test_prob
error_check["predicted_label"] = test_pred

# False positives: model predicted decline, but actual label is 0
false_positives = error_check[
    (error_check[TARGET] == 0) &
    (error_check["predicted_label"] == 1)
].sort_values("predicted_probability", ascending=False)

# False negatives: model predicted no decline, but actual label is 1
false_negatives = error_check[
    (error_check[TARGET] == 1) &
    (error_check["predicted_label"] == 0)
].sort_values("predicted_probability", ascending=True)

print("False positives:", len(false_positives))
print("False negatives:", len(false_negatives))

print("\n=== 3 False Positives ===")
display(false_positives.head(3))

print("\n=== 3 False Negatives ===")
display(false_negatives.head(3))

False positives: 1394
False negatives: 1175

=== 3 False Positives ===

,content_id,client_id,is_declining_label,predicted_probability,predicted_label
26614,content_7be5f150dc65,client_f369cb89fc,0,0.945100,1
20736,content_41baf0722ad9,client_8527a891e2,0,0.932088,1
12869,content_5d5653c4eb4f,client_4e07408562,0,0.917577,1

=== 3 False Negatives ===

,content_id,client_id,is_declining_label,predicted_probability,predicted_label
8407,content_d1e915d03c28,client_4e07408562,1,0.050920,0
29158,content_e18144cbd19d,client_4e07408562,1,0.055430,0
17690,content_c268b1716236,client_e629fa6598,1,0.064807,0

### Three concrete errors

The model makes both false-positive and false-negative errors. A false positive is a page predicted as declining when the observed label is not declining. A false negative is a declining page that the model does not identify.

The three examples below are inspected as difficult cases rather than treated as evidence that the model is wrong for a specific causal reason. Possible explanations include overlapping traffic patterns, content characteristics, search-position differences, and information not represented in the available features.

1. **False positive:** The model assigned a high decline probability, but the observed label was 0. This indicates that the available features looked similar to declining pages even though the observed outcome was not declining.

2. **False positive:** The model again predicted decline but the observed label was 0. This shows that the model can over-prioritize pages with strong signals associated with decline.

3. **False negative:** The observed label was 1, but the model predicted 0. This indicates that some declining pages do not have a feature pattern that the Logistic Regression model can easily distinguish.

### Final conclusion

On the same client-held-out test split, Logistic Regression achieved higher Precision@20 than the ML-07 rule baseline (0.70 vs 0.65), while the baseline achieved higher Precision@50 (0.74 vs 0.72). Therefore, the learned model is not uniformly better than the baseline. It appears useful for prioritizing a smaller top-20 review queue, while the simpler rule remains competitive for a larger top-50 queue. The result is decision-support evidence rather than proof that the model will improve content performance.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.